<div class="footer-divider"></div>

<div class="footer-grid">
    <div class="footer-col issued-by">
        <div class="footer-label">ISSUED BY</div>
        @if ($officer)
            <div class="officer-name">{{ $officer->name }}</div>
            <div class="officer-role">Transportation Enforcement Officer</div>
            <div class="officer-id">Officer ID: {{ $officer->badge_id }}</div>
        @else
            <div class="officer-name">Name of Issuing Officer</div>
            <div class="officer-role">Transportation Enforcement Officer</div>
            <div class="officer-id">Officer ID: TE-000000</div>
        @endif
    </div>
    <div class="footer-col inquiries">
        <div class="footer-label">INQUIRIES</div>
        <div class="inquiry-text">Present {{ $docType }} No.</div>
        <div class="inquiry-number">{{ $docNumber }}</div>
        <div class="inquiry-location">at the TEMS Office.</div>
    </div>
</div>

<div class="footer-divider"></div>

<div class="footer-meta">
    <div class="meta-line">{{ $docType }} No.: {{ $docNumber }}</div>
    <div class="meta-line">Generated by {{ config('itevcms.app_name') }} &bull; {{ now()->format('M d, Y h:i A') }}</div>
    <div class="meta-line system-notice">This is a system-generated document issued through TEMS.</div>
</div>